[package]
name = "lzma-sys"
version = "0.1.0"
authors = ["Sergei Solodovnikov <sergei@isolo.me>"]
edition = "2018"
links = "lzma"
build = "build.rs"
readme = "README.md"

[lib]
crate-type = ["lib"]

[build-dependencies]
autotools = "0.2.2"
pkg-config = "0.3"
build-deps = "0.1"